all:
	cat README.md

codeConfigure:
	code ./apps/go.vsix

codeWorkspace:
	code workspace/src/github.com/Sfeir/handsongo

goWorkspace:
	cd workspace/src/github.com/Sfeir/handsongo

.PHONY: all codeGoplugin codeWorkspace goWorkspace
